from ncompress import compress, decompress
import io

input_text = "EnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezEnekoTelecoMarcIbañezMarcIbañezFINAL!"
file = open("/content/file.txt", "w", encoding='utf-32')
file.write(input_text)
file.close()

file = open("/content/file.txt", "rb")
bytes_file = file.read()
compressed_text = compress(bytes_file)
#print(compressed_text)
print(bytes_file)

decompressed_text = decompress(compressed_text)
print(decompressed_text)
file = open("/content/results.txt", "wb")
file.write(decompressed_text)
file.close()

losses = 33
losses_text = compressed_text[:(-1*losses)]
print(losses_text)

decompressed_text = decompress(losses_text)
print(decompressed_text)
file = open("/content/results_with_losses.txt", "wb")
file.write(decompressed_text)
file.close()
